src/runtime/server/utils/session.ts
Instead of asserting the session data, pass the `UserSession` type as a generic into the h3 `useSession`.
Also, use the `SessionConfig` instead of `any`.
(Although `ts-ignore` is used so it doesn't really do anything, it is more correct)
=> chore: Set `useSession` `SessionDataT` type to `UserSession`

src/runtime/server/lib/oauth/auth0.ts
Forces reauthentication whenever user logs out, and shows Auth0 Universal Login Can be set when defining auth0EventHandler, same as `emailRequired`
=> feat: add max_age param for auth0

src/runtime/server/lib/oauth/auth0.ts
Adds the connection query parameter for Auth0 to the config, which causes the direct use of this connection instead of the default Auth0 login page.
=> feat: add auth0 connection parameter to config

src/runtime/server/lib/oauth/google.ts
The `redirectUrl` on the Google OAuth types should be removed:
- it's not used by any of the code, in fact it's the only provider that has it
- it's a required type so you have to provide it, and it has to be `'/auth/google'`
=> fix(google): remove `redirectUrl` type

src/runtime/server/tsconfig.json
Only fixes the types for `useRuntimeConfig()`, but may be useful in the future. I usually have this as default for server folder and think it's a good practice.
=> chore: server types

README.md, src/module.ts, src/runtime/server/utils/session.ts
=> feat: add replaceUserSession()

README.md, playground/auth.d.ts, src/runtime/server/utils/session.ts, src/runtime/types/index.ts, src/runtime/types/session.ts
Closes #38
Closes #31
It seems like the `user` type inside the `UserSession` interface cannot be augmented directly so I created a separate `User` interface. This does work.
Fixing the possibly `undefined` after using `requireUserSession` is achieved by setting the type explicitly to be defined. (we can do this because we check it to be defined right before returning it)
=> fix: UserSession user type augmentation

playground/app.vue, playground/auth.d.ts, playground/server/routes/auth/auth0.get.ts, playground/server/routes/auth/battledotnet.get.ts, playground/server/routes/auth/cognito.get.ts, playground/server/routes/auth/discord.get.ts, playground/server/routes/auth/github.get.ts, playground/server/routes/auth/google.get.ts, playground/server/routes/auth/keycloak.get.ts, playground/server/routes/auth/linkedin.get.ts, playground/server/routes/auth/microsoft.get.ts, playground/server/routes/auth/spotify.get.ts, playground/server/routes/auth/twitch.get.ts, src/runtime/server/lib/oauth/auth0.ts, src/runtime/server/lib/oauth/battledotnet.ts, src/runtime/server/lib/oauth/cognito.ts, src/runtime/server/lib/oauth/discord.ts, src/runtime/server/lib/oauth/github.ts, src/runtime/server/lib/oauth/google.ts, src/runtime/server/lib/oauth/keycloak.ts, src/runtime/server/lib/oauth/linkedin.ts, src/runtime/server/lib/oauth/microsoft.ts, src/runtime/server/lib/oauth/spotify.ts, src/runtime/server/lib/oauth/twitch.ts, src/runtime/types/oauth-config.ts
Resolves #22
Resolves #43 by overwriting `redirect_uri` in `authorizationParams`
This pull request introduce `authorizationParams` option in each OAuth provider, example:
```ts
export default oauth.googleEventHandler({
config: {
authorizationParams: {
access_type: 'offline'
}
},
async onSuccess(event, { user }) {
// ...
}
})
```
The `authorizationParams` can overwrite the generated params we provide and this can be useful in case such as #43 
```ts
export default oauth.microsoftEventHandler({
config: {
authorizationParams: {
redirect_uri: 'https://my-custom-redirect-uri'
}
},
async onSuccess(event, { user }) {
// ...
}
})
```
=> feat: add authorizationParams in oauth config

src/runtime/server/lib/oauth/microsoft.ts
**Problem Statement**
In the current implementation of the Microsoft OAuth configuration within our Nuxt 3 library, there's no explicit way to define the protocol (HTTP or HTTPS) in the redirect URL. This limitation can lead to mismatches between the protocol used by the application and the callback URL expected by Microsoft's OAuth service, especially in environments where both HTTP and HTTPS are used or during the development stages where HTTP is more common.
**Proposed Solution**
This PR introduces a new configuration option, redirectUrl, to the OAuthMicrosoftConfig. The redirectUrl allows developers to explicitly set the full URL, including the protocol, that will be used as the callback URL in the OAuth flow. This enhancement ensures greater flexibility and control, allowing for …
=> Feature: Add redirectUrl to OAuthMicrosoftConfig for HTTP vs HTTPS Handling

src/runtime/server/utils/session.ts, src/runtime/types/index.ts, src/runtime/types/session.ts
The return value of `requireUserSession` is guaranteed to have the `user` component defined.
Previously, the return type was changed to reflect that fact but the session type passed to the `fetch` hook was not.
(It was not immediately clear to me, but the result of `requireUserSession` is passed into the `fetch` hook)
This fixes that and should avoid users to do an unnecessary check when hooking into `fetch`
Previously:
```ts
export default defineNitroPlugin(() => {
sessionHooks.hook('fetch', (session, event) => {
// session.user is possibly undefined, so we add a guard
if (!session.user)
// Do something
// Do what you actually wanted to do with 'session.user'
});
});
```
With this PR:
```ts
export default defineNitroPlugin(() => {
sessionHooks.hook('fetch', (session, event) => {
// …
```
=> fix: narrowed session type passed to `fetch` session hook

src/runtime/composables/session.ts
The nitro session fetch hook is likely to be used for implementing the necessary checks to ensure token validity, this might require making additional network requests to the pertinent authentication server.
The current implementation results in the aforementioned checks being made twice whenever the **session cookie is present**, and the **earlier checks have failed** (_returned `throw createError()` within session fetch hook_), hence resulting in unnecessary overhead.
=> fix: avoid duplicate trigger of session fetch hook due to request retry

playground/server/plugins/session.ts, src/module.ts, src/runtime/server/lib/oauth/facebook.ts, src/runtime/server/plugins/oauth.ts
* Facebook provider was only fetching 'id' and 'name' fields, I have added config.fields support.
* Facebook login redirects with /#_=_ , to avoid ugly and wrong url hash, I have added how to remove it efficiently with nuxt3 server hooks to playground, (https://stackoverflow.com/questions/7131909/facebook-callback-appends-to-return-url)
=> feat: add fields support to facebook provider

src/runtime/server/lib/oauth/auth0.ts, src/runtime/server/lib/oauth/battledotnet.ts, src/runtime/server/lib/oauth/cognito.ts, src/runtime/server/lib/oauth/discord.ts, src/runtime/server/lib/oauth/facebook.ts, src/runtime/server/lib/oauth/github.ts, src/runtime/server/lib/oauth/google.ts, src/runtime/server/lib/oauth/keycloak.ts, src/runtime/server/lib/oauth/linkedin.ts, src/runtime/server/lib/oauth/microsoft.ts, src/runtime/server/lib/oauth/spotify.ts, src/runtime/server/lib/oauth/twitch.ts
=> refactor: replace ofetch with $fetch

.github/workflows/autofix.yml, .vscode/settings.json, package.json
Hello,
Since the ESLint config use `stylistic`, it make sens to add a script to lint the repo. In the meantime, I add a setting to disable the prettier extension to avoid conflict.
=> style: add lint script

playground/app.vue, src/runtime/app/components/AuthState.vue
**Problem**
No type suggestions when use slot props
**Solution**
Add lang="ts" for component script tag
**Test**
Clone demo from readme
https://github.com/atinux/nuxt-todos-edge
- Add in app.vue AuthState component with use slot props
```
...
<AuthState v-slot="userSession">
{{ userSession}}
</AuthState>
<NuxtPage />
...
```
- pnpm i
- pnpm dev
- check userSession type (in AuthState component)  -> any
- go manually into AuthState component and add lang="ts" in <script
- remove .nuxt, run pnpm dev and reload ts server/ window (ctrl+shift+p >Developer:reload window)
- Check userSesstion type
I also think that the documentation is not entirely correct because you need to use loggedIn.value instead of loggedIn.
=> fix: add missing lang=ts for correct slot props types

src/runtime/server/api/session.get.ts, test/basic.test.ts
=> fix: always return 200 for session endpoint

src/module.ts
This PR seeds `runtimeConfig.oauth.microsoft.redirectUrl` so that a `NUXT_OAUTH_MICROSOFT_REDIRECT_URL` var will be applied without further configuration in nuxt.config.
=> feat: support `NUXT_OAUTH_MICROSOFT_REDIRECT_URL`

src/module.ts, src/runtime/server/utils/session.ts
Added support for custom prefix. Necessary function when the application is not using `NUXT_`, but its own e.g. `APP_`.
Resolves #132
=> feat: add support nitro prefix env

src/runtime/server/lib/oauth/cognito.ts
Hey there,
We have a AWS Cognito Pool configured to use a custom domain for the hosted UI ([docs on that](https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-pools-add-custom-domain.html)).
During that configuration you can choose to delete the provided Cognito domain (Step 1.5 in the docs, see their note) – `${config.userPoolId}.auth.${config.region}.amazoncognito.com`. If that occurs then the existing implementation of `oauthCognitoEventHandler` doesn't work.
This PR adds the functionality to provide the custom domain via the provider config. If `config.domain` isn't set then the default will still be made using `config.userPoolId` and `config.region`.
=> feat: cognito oauth support custom domain

package.json, pnpm-lock.yaml, src/runtime/server/lib/oauth/auth0.ts, src/runtime/server/lib/oauth/battledotnet.ts, src/runtime/server/lib/oauth/cognito.ts, src/runtime/server/lib/oauth/discord.ts, src/runtime/server/lib/oauth/facebook.ts, src/runtime/server/lib/oauth/github.ts, src/runtime/server/lib/oauth/google.ts, src/runtime/server/lib/oauth/keycloak.ts, src/runtime/server/lib/oauth/linkedin.ts, src/runtime/server/lib/oauth/microsoft.ts, src/runtime/server/lib/oauth/paypal.ts, src/runtime/server/lib/oauth/spotify.ts, src/runtime/server/lib/oauth/steam.ts, src/runtime/server/lib/oauth/twitch.ts, src/runtime/server/lib/oauth/x.ts, src/runtime/server/lib/oauth/xsuaa.ts, src/runtime/server/lib/oauth/yandex.ts, src/runtime/server/lib/utils.ts, src/runtime/types/index.ts, src/runtime/types/oauth-config.ts
Hello 👋,
This PR tries to unify the way configuration errors are handled by creating a single function `handleMissingConfiguration`.
This is the first PR in a series trying to simplify each provider event handler and standardize errors and reducing code redundancy.
This reduce the bundle size (`dist/runtime`) from 84.1ko to 83.7ko
=> refactor: handle missing configuration error

src/runtime/server/lib/oauth/paypal.ts
Hello! This PR re-adds the `encodeURIComponent` to the `redirect_uri` when fetching tokens.
I noticed the utils refactor in #147 broke PayPal login because the `redirect_uri` encode was removed, I should have left a comment in the code when I made the PayPal provider PR (#108) saying that at the moment PayPal login for some reason requires encoding the `redirect_uri` when fetching the tokens.
For testing:
1. Login in sandbox mode https://developer.paypal.com/dashboard/applications/sandbox
2. Go to `REST API apps` Click on `Default Application`
3. Copy `Client ID` and `Secret key 1`
4. Create a `.env` file and add the credentials respectively `NUXT_OAUTH_PAYPAL_CLIENT_ID` and `NUXT_OAUTH_PAYPAL_CLIENT_SECRET`
5. Scroll down to the `Features` section, and enable `Log in with PayPal`
6. …
=> fix: paypal tokens request requires encoded  `redirect_uri`

README.md
Closes https://github.com/atinux/nuxt-auth-utils/issues/165.
Adds a note to the README describing the `api/_auth/session` API route used by Nuxt Auth Utils, and cautioning that middleware should not be applied to this route. 
Justification: it would have saved me some time to know about this route when I was debugging why my implementation of Nuxt Auth Utils was not working properly. (And it seems that others besides me may have had this issue, cf https://github.com/atinux/nuxt-auth-utils/issues/111)
=> docs: Add note to readme about session API route

README.md, src/runtime/types/index.ts, src/runtime/types/session.ts
Seems like `secure` type (https://github.com/atinux/nuxt-auth-utils/blob/main/src/runtime/types/session.ts#L14) can't be augmented just like in #54. This PR extracts the `secure` property type to a separated interface `SecureSessionData` that allows augmentation/overriding the default typings.
This would allow to add better typing to the `secure` property:
```ts
// auth.d.ts
declare module '#auth-utils' {
interface SecureSessionData {
token: string
}
}
export {}
```
=> fix: UserSession secure type augmentation

src/runtime/server/api/session.get.ts
resolves #175 
This is a breaking change is you are using the `fetch` hook as it is now called anytime a session is set, whatever is the `user` is set or not, see #175 for use cases.
=> feat!: call `fetch` hook whatever is `session.user` is defined or not

src/runtime/server/lib/oauth/google.ts
This update add the state parameter to the Google OAuth flow to enhance security and help maintain state between the request and callback.
For more details: [Google OAuth 2.0 - Request Parameter: state](https://developers.google.com/identity/protocols/oauth2/web-server#request-parameter-state).
=> chore: add `state` params in Google oauth

playground/auth.d.ts, playground/middleware/jtw.global.ts, playground/package.json, playground/pages/about.vue, playground/pages/index.vue, playground/server/api/jtw/create.post.ts, playground/server/api/jtw/payload.get.ts, playground/server/api/jtw/refresh.post.ts, pnpm-lock.yaml, src/runtime/app/composables/session.ts
This is initial work to have a better way to deal with refresh tokens (#91)
IMO, the refresh tokens should be implemented using an app middleware that run during SSR or client-side navigation (skipping it during hydration).
I added an example in the playground to move forward and simplify as much as possible the refresh middleware.
This pull request starts simple by adding the ability to forward the cookie back to the main SSR request when calling the `clear()` method, useful if both access token and refresh tokens are expired.
I also added an example for the refresh middleware.
Later on, I plan to work on a `$authFetch` (or $api)  to make sure the requests done are up to date in term of cookie headers as well as adding listener to automatically refresh the user/session from …
=> feat: forward set-cookie header for `useUserSession().clear()`

README.md, playground/server/api/webauthn/register.post.ts, src/runtime/app/composables/webauthn.ts, src/runtime/server/lib/webauthn/register.ts, src/runtime/types/webauthn.ts
resolves #272 
By giving the `event` as 2nd argument to `validateUser(userBody, event)`, we can now check if the user is authenticated to check if the `user.userName` is part of the userSession.
Example:
```ts
export default defineWebAuthnRegisterEventHandler({
// optional
async validateUser(userBody, event) {
// bonus: check if the user is already authenticated to link a credential to his account
// We first check if the user is already authenticated by getting the session
// And verify that the email is the same as the one in session
const session = await getUserSession(event)
if (session.user?.email && session.user.email !== body.userName) {
throw createError({ statusCode: 400, message: 'Email not matching curent session' })
}
// If he registers a new account with credentials
return …
```
=> feat(webauthn): add event to validateUser to track authenticated users

src/runtime/server/lib/oauth/workos.ts
resolves issue: #289 
Although this isn't required it is something that would be nice to support.
=> feat: adding organization_id option for WorkOS provider

src/runtime/server/lib/oauth/instagram.ts
Resolves #193 
This both upgrades the Instagram provider to use the new login system (only business and creator accounts are allowed), as well as adds some typing and better error data.
The two most important upstream documentation are:
1. [here](https://developers.facebook.com/docs/instagram-platform/instagram-api-with-instagram-login/create-a-meta-app-with-instagram) for creating a meta app.
2. [here](https://developers.facebook.com/docs/instagram-platform/instagram-api-with-instagram-login/get-started) for details on what fields to use for retrieving specific user's data
3. [here](https://developers.facebook.com/docs/instagram-platform/instagram-api-with-instagram-login/business-login) for more advanced scoped access to authorize for things like messages and content management. …
=> fix(instagram): oauth provider

package.json, pnpm-lock.yaml, src/runtime/server/lib/oauth/cognito.ts
Added OIDC discovery for Cognito to automatically use authentication endpoints and hosted UI domains that have been configured by the IDP in AWs.
=> feat(cognito): integrate OpenID Connect discovery for improved OAuth flow

src/runtime/server/lib/oauth/github.ts
Use-case: Was creating an email verification system, and I would like to bypass the need for reverification on new accounts if the user already has an email verified in GitHub.
To avoid duplicate requests to the GitHub emails endpoint in the `onSuccess` in my app, I think it's better if the library already provided that info, since it already has access to if `emailRequired` is set to `true`.
=> feat: set `email_verified` in `user` on GitHub provider

playground/app.vue, src/runtime/server/lib/atproto/bluesky.ts
Use local map to store session. Previously, the cookie method couldn't work because a `setCookie` sets the cookie in the response, and not in the current request.
This also fixes an issue on the playground where the click handler was discarded if not using a popup
=>  fix(bluesky): use local map for session storing

package.json, pnpm-lock.yaml
fixes: #343 
the major versions of `@simplewebauthn/browser`, `@simplewebauthn/server` and `@simplewebauthn/types` needs to be the same.
=> fix: align @simplewebauthn/types version

playground/server/routes/auth/apple.ts, src/runtime/server/lib/oauth/apple.ts
The current implementation of the Apple return is a completely different from other providers (e.g. Google, Facebook).
In the current implementation, tokens are not returned as tokens but payload, which is very problematic when you want to use tokens and the same flow as for the rest of the providers, e.g. sending access_token to an additional backend.
Google returns:
- { tokens: { access_token}
Facebook returns:
- { tokens: { access_token }
the rest of the providers in the repository are similar, and apple returns the decoded jwt as tokens :/
=> fix(oauth, apple): return tokens in response

src/runtime/server/lib/oauth/facebook.ts
This fix ensures that `config.fields` and `config.scope` does not get duplicated when merging the provided configuration with the runtime configuration using `defu`. Previously, multiple merges could lead to redundant entries in `config.fields`.
- Updated `oauth/facebook.ts` to correctly handle merging behavior.
- Added a safeguard to prevent `config.fields` and `config.scope` duplication.
- The previous behavior caused unnecessary field repetitions, leading to potential runtime errors when scope or fields were explicitly defined in the configuration.
- Created a new const runtimeConfig outside defu to prevent duplicate fields and scope entries during the merge process.
- Manually tested with different configurations to ensure no duplicates are created.
=> fix(oauth, facebook): prevent duplication of config.fields and config.scope in defu merge

src/runtime/server/lib/oauth/github.ts
Replace `https://api.github.com` by a config variable so that GitHub Enterprise Server and GHE.com can be supported. Those are not only different DNS entries but also different formats: `https://<server>/api/v3`, `https://api.<tenant>.ghe.com`
=> feat: support GitHub Enterprise Server and GHE.com

src/runtime/server/lib/oauth/facebook.ts, src/runtime/server/lib/oauth/microsoft.ts
- Added support for the `state` parameter in the Facebook OAuth configuration.
- Encoded the `state` parameter as a JSON string to allow custom data to be passed (e.g., redirect subdomain).
=> feat: add support for authorization parameters and ensure state param is included from query when present in Facebook & Microsoft OAuth

src/runtime/server/lib/oauth/zitadel.ts, src/runtime/server/lib/utils.ts
This PR adds the PKCE flow to the Zitadel provider as it's recommended by the provider, inspired by what was done in `azureb2c` provider.
=> feat(zitadel) use more secure PKCE flow

src/module.ts, src/runtime/server/utils/session.ts
This change updates handling of session password generation. It no longer manually sets the environment variable to the `runtimeConfig`, which acted as a default and included in the production build. Instead, it checks during dev that the environment variable is present or not. Loading the runtime config from environment should be handled by `nuxt` in future runs.
=> fix: prevent session password in .env from being included in production builds
